const mongoose = require('mongoose');
const pagination = require('mongoose-paginate-v2')
const BillSchema = new mongoose.Schema({

   
    
    created:{
        type:Date,
        default:Date.now
    },
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"User"
    },
    header_company_name:{
        type:String
    },
    bill_no:{
        type:String
    },
    ho_address:{
        type:String,
        trim:true
    },
    bo_address:{
        type:String,
        trim:true
    },
    gc_no:{
        type:String
    },
    gc_date:{
        type:String
    },
    unload_date:{
        type:String
    },
    bill_date:{
        type:String
    },
    start_location:{
        type:String
    },
    destination_location:{
        type:String
    },
    vehicle_no:{
        type:String
    },
    vehicle_type:{
        type:String
    },
    branch:{
        type:String
    },
    invoice_no:{
        type:String
    },
    invoice_date:{
        type:String
    },
    consignee_name:{
        type:String
    },
    consignee_address:{
        type:String
    },
    consignee_gst:{
        type:String
    },
    consignee_state_code:{
        type:String
    },
    consignor_name:{
        type:String
    },
    consignor_address:{
        type:String
    },
    consignor_gst:{
        type:String
    },
    consignor_state_code:{
        type:String
    },
    entries:[
        {   _id:false,
            description:{
                type:String,
                trim:true
            },
            weight:{
                type:String
            },
            freight:{
                type:String
            },
            total:{
                type:String
            }

        }
    ],
    sub_total:{
        type:String
    },
    lr_charge:{
        type:String
    },
    labour_charge:{
        type:String
    },
    waiting_charge:{
        type:String
    },
    total_amount:{
        type:String
    },
    amount_in_words:{
        type:String
    },
    bill_for_company_name:{
        type:String
    },
    optional_signature_text:{
        type:String
    },
    bank_name:{
        type:String
    },
    bank_branch:{
        type:String
    },
    bank_account_no:{
        type:String
    },
    bank_ifsc_code:{
        type:String
    },
    gst_in:{
        type:String
    },
    pan_no:{
        type:String
    },
    gst_paid_by:{
        type:String
    },
    bill_type:{     //Bill,LR,Loading Advice
        type:String
    },
    doc_type:{          //info-doc,saved-doc
        type:String
    },
    bill_created_date:{
        type:String
    },
    lr_created_date:{
        type:String
    },
    company:{
        type:mongoose.Schema.ObjectId,
        ref:'Company'
    },
    truck:{
        type:mongoose.Schema.ObjectId,
        ref:'Truck'
    },
    consignment:{
        type:mongoose.Schema.ObjectId,
        ref:'Consignment'
    },
    bill_name:{
        type:String
    },
    lr_no:{
        type:String
    },
    value_rs:{
        type:String
    },
    lr_entries:[
        {
            _id:false,
            no_of_articles:{
                type:String
            },
            description:{
                type:String,
                trim:true
            },
            weight_actual:{
                type:String
            },
            weight_charged:{
                type:String
            },
            amount_to_pay:{
                type:String
            },
            amount_paid:{
                type:String
            }
        }
    ],
    delivery_address:{
        type:String
    },
    delivery_number:{
        type:String
    },
    shipment_number:{
        type:String
    },
    office_number:{
        type:String
    },
    consignee_gst_check:{
        type:Boolean,
        default:false
    },
    consignor_gst_check:{
        type:Boolean,
        default:false
    },
    transporter_gst_check:{
        type:Boolean,
        default:false
    },
    hamali_charge:{
        type:String
    },
    dd_charge:{
        type:String
    },
    local_charge:{
        type:String
    },
    bilty_charge:{
        type:String
    },
    service_charge:{
        type:String
    },
    contact_no_1:{
        type:String
    },
    contact_no_2:{
        type:String
    },
    load_tonnes:{
        type:String
    },
    rate_per_tonne:{
        type:String
    },
    advance_amount:{
        type:String
    },
    lorry_freight:{
        type:String
    },
    ms_company_name:{
        type:String
    },
    balance:{
        type:String
    },
    payable:{
        type:String
    },
    bill_images:[
        {
            type:String
        }
    ],
    remarks:{
        type:String,
        trim:true,
    },
    delivery_charge:String

    


})

BillSchema.plugin(pagination);

module.exports = mongoose.model('Bill',BillSchema);