const mongoose = require('mongoose');
const pagination = require('mongoose-paginate-v2')
const ConsignmentSchema = new mongoose.Schema({
    total_distance:{
        type:Number
    },
    estimated_time:{
        type:String
    },
    total_time_taken:{
        type:String
    },
    start_location_name:{
        type:String
    },
    destination_name:{
        type:String
    },
    delivery_status:{
        type:String,
        default:'Pending'
    },
    truck_image:{
        type:String
    },
    bill_images:[{
        type:String
    }],
    bills:[{
        type:mongoose.Schema.ObjectId,
        ref:'Bill'
    }],
    fine_images:[{
        type:String
    }],
    fines:[{
        _id:false,
        location:{
            type:String
        },
        amount:{
            type:Number
        },
        reason:{
            type:String
        },
        date:{
            type:String
        }
    }],
    additional_bill_images:[{
        type:String
    }],
    pickup_type:{
        type:String
    },
    single_pickup_location:{
        type:String
    },
    multiple_pickup_location:[{
        type:String
    }],
    delivery_type:{
        type:String
    },
    single_delivery_location:{
        type:String
    },
    multiple_delivery_location:[{
        type:String
    }],
    primary_driver:{
        type:mongoose.Schema.ObjectId,
        ref:'User'
    },
    assist_driver:{
        type:mongoose.Schema.ObjectId,
        ref:'User'
    },
    truck:{
        type:mongoose.Schema.ObjectId,
        ref:'Truck'
    },
    goods_type:{
        type:String
    },
    weight_of_goods_without_truck_before_pickup:{
        type:Number
    },
    weight_of_goods_with_truck_before_pickup:{
        type:Number
    },
    weight_of_goods_without_truck_delivered:{
        type:Number
    },
    weight_of_goods_with_truck_delivered:{
        type:Number
    },
    fuel_before_pickup:{
        type:Number
    },
    fuel_after_delivery:{
        type:Number
    },
    total_amount_used_for_fuel:{
        type:Number
    },
    additional_expenses:[{
        _id:false,
        expense_info:{
            type:String
        },
        total_cost:{
            type:Number
        },
        paid_to_driver:{
            type:Number
        },
        date:{
            type:String
        }
    }],
    total_distance_covered_by_truck:{
        type:Number
    },
    additional_distance_covered_by_truck:{
        type:Number
    },
    fuel_filled_location:[{
        _id:false,
        location:{
            type:String
        },
        amount:{
            type:Number
        },
        fuel_before_filling:{
            type:Number
        },
        fuel_after_filling:{
            type:Number
        },
        time_spent:{
            type:String
        },
        created:{
            type:Date,
            default:Date.now
        }
    }],
    company:{
        type:mongoose.Schema.ObjectId,
        ref:'Company'
    },
    total_payable_amount_before_pickup:{
        type:Number
    },
    total_payable_amount_after_delivery:{
        type:Number
    },
    advance_payment:{
        type:Number
    },
    estimated_final_payment_time:{
        type:String
    },
    delivered_date:Date,
    stoppages:[{
        _id:false,
        location:{
            type:String
        },
        time_spent:{
            type:String
        },
        arrived_at:{
            type:String
        },
        departed_at:{
            type:String
        },
        fuel_on_arrival:{
            type:Number
        },
        fuel_on_departure:{
            type:Number
        },
        created:{
            type:Date,
            default:Date.now
        }
    }],
    vehicle_damage:{
        type:Boolean,
        default:false
    },
    final_delivery_status:{
        type:String,
        default:'pending'
    },
    vehicle_damage_types:[{
        _id:false,
        damage_type:{
            type:String
        },
        amount_charged:{
            type:Number
        },
        time_to_repair:{
            type:String
        },
        date:{
            type:String
        }
    }],
    pending_payment:{
        type:Number
    },
    all_bills_submitted:{
        type:Boolean,
        default:false
    },
    tolls:[{
        _id:false,
        location:{
            type:String
        },
        amount:{
            type:Number
        },
        created:{
            type:Date,
            default:Date.now
        }
    }],
    total_freight:{
        type:Number
    },
    pod_received_date:{
        type:String
    },
    pod_submitted_date:{
        type:String   
    },
    amount_paid_till_now:{
        type:Number
    },
    balance_amount_remaining:{
        type:Number
    },
    balance_receive_date:{
        type:String
    },
    fuel_reading_on_trip_start:{
        type:String
    },
    fuel_reading_on_trip_end:{
        type:String
    },
    note:{
        type:String,
        trim:true
    },
    late_charge_applicable:{
        type:Boolean,
        default:false
    },
    total_late_charge_amount:{
        type:Number
    },
    total_late_unloading_days:{
        type:String
    },
    late_charge_per_day:[
        {
            type:String
        }
    ],
    delivery_start_date:{
        type:String
    },
    delivery_end_date:{
        type:String
    },
    created:{
        type:Date,
        default:Date.now
    },
    user:{
        type:mongoose.Schema.ObjectId,
        ref:'User'
    }

    

})

ConsignmentSchema.plugin(pagination);

module.exports = mongoose.model('Consignment',ConsignmentSchema);