const mongoose = require('mongoose');
const pagination = require('mongoose-paginate-v2');
const TruckSchema = new mongoose.Schema({

    vehicle_no:{
        type:String,
        required:true
    },
    vehicle_registered_date:{
        type:String
    },
    vehicle_images:[{
        type:String
    }],
    vehicle_document_images:[{
        type:String
    }],
    vehicle_driver:{
        type:mongoose.Schema.ObjectId,
        ref:'User'
    },
    assist_driver:{
        type:mongoose.Schema.ObjectId,
        ref:'User'
    }, 
    previous_drivers:[{
        type:mongoose.Schema.ObjectId,
        ref:'User'
    }],
    current_location:{
        type:String
    },
    previous_consignment:{
        type:mongoose.Schema.ObjectId,
        ref:'Consignment'
    },
    current_consignment:{
        type:mongoose.Schema.ObjectId,
        ref:'Consignment'
    },
    delivery_status:{
        type:String
    },
    fuel_tank_capacity:{
        type:Number
    },
    vehicle_type:{
        type:String
    },
    total_tyres:{
        type:Number
    },
    vehicle_dimensions:{
        _id:false,
        length:{
            type:String
        },
        breadth:{
            type:String
        },
        width:{
            type:String
        }
    },
    vehicle_repair_history:[{
        _id:false,
        repair_type:{
            type:String
        },
        cost:{
            type:Number
        },
        reason:{
            type:String
        },
        repaired_by:{
            type:String
        },
        date_of_submit:{
            type:String
        },
        date_of_return:{
            type:String
        }
        
    }],
    vehicle_deliveries:[{
        type:mongoose.Schema.ObjectId,
        ref:'Consignment'
    }],
    distance_travelled:{
        type:String
    },
    vehicle_bills:[{
        type:mongoose.Schema.ObjectId,
        ref:'Bill'
    }],
    current_fuel:{
        type:Number
    },
    delivery_route_history:[{
        _id:false,
        from:{
            type:String
        },
        to:{
            type:String
        },
        start_date:{
            type:String
        },
        end_date:{
            type:String
        },
        cost_incurred:{
            type:String
        }
    }],
    vehicle_idle_time:[{
        _id:false,
        location:{
            type:String
        },
        idle_time:{
            type:String
        },
        date:{
            type:String
        }
    }],
    vehicle_current_status:{   //idle,deliverying,wait for unload
        type:String
    },
    vehicle_insurance_status:{
        valid_from:{
            type:String
        },
        valid_till:{
            type:String
        }
    },
    vehicle_buy_date:{
        type:String
    },
    vehicle_added_to_collection_date:{
        type:String
    },
    created:{
        type:Date,
        default:Date.now
    },
    user:{
        type:mongoose.Schema.ObjectId,
        ref:'User'
    }


})

TruckSchema.plugin(pagination)
module.exports = mongoose.model('Truck',TruckSchema);